// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import dotenv from "dotenv";
import path from "path";
import { defineConfig } from "prisma/config";

dotenv.config({
  path: path.resolve(import.meta.dirname, "../../.env"),
});

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Placeholder is enough for `prisma generate`; a real DATABASE_URL is required at runtime.
    url:
      process.env.DATABASE_URL ??
      "postgresql://postgres:postgres@localhost:5432/daisycode",
  },
});
